name: Linting CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: cd ./packages/web && npm install

    - name: Frontend Eslint
      run: cd ./packages/web && npm run lint

    - name: Frontend Prettier
      run: cd ./packages/web && npm run format:fix

    - name: Server Eslint
      run: cd ./packages/server && npm run lint

    - name: Server Prettier
      run: cd ./packages/server && npm run format:fix
